version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: default
      POSTGRES_DB: appointify
    ports:
      - "5432:5432"

  java_app:
    image: rodrigotopan/appointify-service:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/appointify